# Generated by Django 5.1.7 on 2025-08-09 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del contacto', max_length=100)),
                ('apellido_pat', models.CharField(blank=True, help_text='Apellido paterno del contacto', max_length=100)),
                ('apellido_mat', models.CharField(blank=True, help_text='Apellido materno del contacto', max_length=100)),
                ('empresa', models.CharField(blank=True, help_text='Empresa donde trabaja el contacto', max_length=150)),
                ('cargo', models.CharField(blank=True, help_text='Cargo o posición del contacto', max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento del contacto', null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el contacto')),
                ('favorito', models.BooleanField(default=False, help_text='Marca este contacto como favorito')),
                ('activo', models.BooleanField(default=True, help_text='Indica si este contacto está activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['nombre', 'apellido_pat'],
            },
        ),
        migrations.CreateModel(
            name='DireccionContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(help_text='Calle y número', max_length=200)),
                ('ciudad', models.CharField(help_text='Ciudad', max_length=100)),
                ('estado_provincia', models.CharField(help_text='Estado o provincia', max_length=100)),
                ('codigo_postal', models.CharField(help_text='Código postal', max_length=20)),
                ('pais', models.CharField(default='México', help_text='País', max_length=100)),
                ('principal', models.BooleanField(default=False, help_text='Marca esta dirección como principal para el contacto')),
                ('activo', models.BooleanField(default=True, help_text='Indica si esta dirección está activa')),
            ],
            options={
                'verbose_name': 'Dirección de Contacto',
                'verbose_name_plural': 'Direcciones de Contacto',
            },
        ),
        migrations.CreateModel(
            name='EmailContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Dirección de email', max_length=254)),
                ('principal', models.BooleanField(default=False, help_text='Marca este email como principal para el contacto')),
                ('activo', models.BooleanField(default=True, help_text='Indica si este email está activo')),
            ],
            options={
                'verbose_name': 'Email de Contacto',
                'verbose_name_plural': 'Emails de Contacto',
            },
        ),
        migrations.CreateModel(
            name='TelefonoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número de teléfono', max_length=20, validators=[django.core.validators.RegexValidator(message="El número debe tener entre 9 y 15 dígitos. Puede incluir el símbolo '+'.", regex='^\\+?1?\\d{9,15}$')])),
                ('principal', models.BooleanField(default=False, help_text='Marca este teléfono como principal para el contacto')),
                ('activo', models.BooleanField(default=True, help_text='Indica si este teléfono está activo')),
            ],
            options={
                'verbose_name': 'Teléfono de Contacto',
                'verbose_name_plural': 'Teléfonos de Contacto',
            },
        ),
        migrations.CreateModel(
            name='TipoDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Tipo de dirección (ej: Casa, Trabajo, Temporal)', max_length=30, unique=True)),
                ('icono', models.CharField(blank=True, help_text='Nombre del icono para mostrar en la interfaz', max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Dirección',
                'verbose_name_plural': 'Tipos de Dirección',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Tipo de email (ej: Personal, Trabajo, Académico)', max_length=30, unique=True)),
                ('icono', models.CharField(blank=True, help_text='Nombre del icono para mostrar en la interfaz', max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Email',
                'verbose_name_plural': 'Tipos de Email',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoRelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del tipo de relación (ej: Familiar, Trabajo, Amigos)', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional del tipo de relación', null=True)),
                ('color', models.CharField(default='#007bff', help_text='Color hexadecimal para identificar visualmente el tipo (#RRGGBB)', max_length=7)),
                ('activo', models.BooleanField(default=True, help_text='Indica si este tipo de relación está disponible para usar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Relación',
                'verbose_name_plural': 'Tipos de Relación',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoTelefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Tipo de teléfono (ej: Móvil, Casa, Trabajo)', max_length=30, unique=True)),
                ('icono', models.CharField(blank=True, help_text='Nombre del icono para mostrar en la interfaz', max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Teléfono',
                'verbose_name_plural': 'Tipos de Teléfono',
                'ordering': ['nombre'],
            },
        ),
    ]
