# Generated by Django 5.1.7 on 2025-08-09 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Contactos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario propietario de este contacto', on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='direccioncontacto',
            name='contacto',
            field=models.ForeignKey(help_text='Contacto al que pertenece esta dirección', on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='Contactos.contacto'),
        ),
        migrations.AddField(
            model_name='emailcontacto',
            name='contacto',
            field=models.ForeignKey(help_text='Contacto al que pertenece este email', on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='Contactos.contacto'),
        ),
        migrations.AddField(
            model_name='telefonocontacto',
            name='contacto',
            field=models.ForeignKey(help_text='Contacto al que pertenece este teléfono', on_delete=django.db.models.deletion.CASCADE, related_name='telefonos', to='Contactos.contacto'),
        ),
        migrations.AddField(
            model_name='direccioncontacto',
            name='tipo',
            field=models.ForeignKey(help_text='Tipo de dirección', on_delete=django.db.models.deletion.PROTECT, to='Contactos.tipodireccion'),
        ),
        migrations.AddField(
            model_name='emailcontacto',
            name='tipo',
            field=models.ForeignKey(help_text='Tipo de email', on_delete=django.db.models.deletion.PROTECT, to='Contactos.tipoemail'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='tipo_relacion',
            field=models.ForeignKey(help_text='Tipo de relación con este contacto', on_delete=django.db.models.deletion.PROTECT, related_name='contactos', to='Contactos.tiporelacion'),
        ),
        migrations.AddField(
            model_name='telefonocontacto',
            name='tipo',
            field=models.ForeignKey(help_text='Tipo de teléfono', on_delete=django.db.models.deletion.PROTECT, to='Contactos.tipotelefono'),
        ),
        migrations.AlterUniqueTogether(
            name='emailcontacto',
            unique_together={('contacto', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='contacto',
            unique_together={('usuario', 'nombre', 'apellido_pat', 'apellido_mat')},
        ),
        migrations.AlterUniqueTogether(
            name='telefonocontacto',
            unique_together={('contacto', 'numero')},
        ),
    ]
